= Setup Oracle SQLcl Action
:linkattrs:
:project-owner: gvenzl
:project-name:  setup-oracle-sqlcl
:project-tag:   v1

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

image:https://img.shields.io/github/v/release/{project-owner}/{project-name}["GitHub release", link="https://github.com/{project-owner}/{project-name}/releases"]

Sets up the link:https://www.oracle.com/database/sqldeveloper/technologies/sqlcl/[Oracle SQLcl] command line tool. This action locates
a given version of Oracle SQLcl, downloads it, and configures the `PATH` environment variable so that SQLcl can be invoked via `sql`.
An environment variable `SQLCL_HOME` also points to the location where the given SQLcl version was installed.

Supported platforms:

 - Linux
 - MacOS
 - Windows

== Inputs

Following inputs may be used as `step.with` keys:

[%header,cols="<2,<,<,<3",width="100%"]
|===
| Name               | Required | Default  | Description
| version            |          | latest   | A valid version of SQLcl from the link:https://www.oracle.com/database/sqldeveloper/technologies/sqlcl/download/[download] site.
| setup-java-version |          | 21       | Automatically setup Oracle JDK with the chosen version. Set to `false` to skip it.
|===

NOTE: If you decide to skip the automatic Java setup then you'll be responsible for configuring Java with version `11` as a minimum.
We recommend using link:https://github.com/actions/setup-java[actions/setup-java].

== Usage

[source,yaml]
[subs="attributes"]
----
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: {project-owner}/{project-name}@{project-tag}
      - name: Run SQLcl
        run: |
          ${SQLCL_HOME}/bin/sql &lt;arguments&gt;
----

== Versions

The full list of supported SQLcl versions can be found link:https://github.com/gvenzl/setup-oracle-sqlcl/blob/main/versions.txt[here].
Use `version: latest` (default & recommended) to always pull the latest release of SQLcl or use an explicit version of SQLcl to pin it for reproducible builds.
